In [2]:
#Q1_0111. 아래 배열에 제곱한 경우와 제곱근의 경우를 계산하여 출력하세요

import numpy as np

# 주어진 배열
array = np.array([1, 2, 3, 4])

# 제곱
squared = array ** 2

# 제곱근
sqrt = np.sqrt(array)

squared, sqrt  # 결과 출력   1 다음에 공백이 많은건 다른 열 값들의 길이와 맞추려고 해서 그런 것





(array([ 1,  4,  9, 16]),
 array([1.        , 1.41421356, 1.73205081, 2.        ]))

In [3]:
# Q2_0111. ar을 하나 만들고 reshape() 함수 이용하여, 임의의 1차원, 2차원, 3차원 배열을 생성해보세요

import numpy as np

# 1차원 배열 생성
ar = np.arange(12)

# 2차원 배열로 변형
ar_2d = ar.reshape(4, 3)

# 3차원 배열로 변형
ar_3d = ar.reshape(2, 2, 3)

ar, ar_2d, ar_3d

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]]]))

In [7]:
#Q3_0111. 배열 변경

# 1차원 배열 생성
array_1d = np.arange(6)  # 0부터 5까지의 요소를 가진 1차원 배열

# 1차원 -> 2차원 변환 (-1 사용)
array_2d = array_1d.reshape(2, -1)  # 2행으로 변환, 열의 크기는 자동으로 결정  -1 을 쓰면 2행에 요소값 6개를 자동으로 열로 하는것 여기선 열이 3열로 알아서 계산 됨

# 1차원 -> 3차원 변환 (-1 사용)
array_3d = array_1d.reshape(2, -1, 1)  # 2x3x1 크기의 3차원 배열로 변환

# 2차원 배열 생성 (예: 2x3)
array_2d_original = np.array([[0, 1, 2], [3, 4, 5]])

# 2차원 -> 1차원 변환
array_1d_from_2d = array_2d_original.reshape(-1)  # 1차원 배열로 평탄화

# 2차원 -> 3차원 변환 (-1 사용)
array_3d_from_2d = array_2d_original.reshape(1, 2, -1)  # 1x2x3 크기의 3차원 배열로 변환

# 3차원 배열 생성 (예: 2x2x3)
array_3d_original = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])

# 3차원 -> 1차원 변환
array_1d_from_3d = array_3d_original.reshape(-1)  # 1차원 배열로 평탄화

# 3차원 -> 2차원 변환 (-1 사용)
array_2d_from_3d = array_3d_original.reshape(2, -1)  # 2행으로 변환, 열의 크기는 자동으로 결정

# 출력
print("1D_to_2D:")
print(array_2d)
print("\n1D_to_3D:")
print(array_3d)
print("\n2D_to_1D:")
print(array_1d_from_2d)
print("\n2D_to_3D:")
print(array_3d_from_2d)
print("\n3D_to_1D:")
print(array_1d_from_3d)
print("\n3D_to_2D:")
print(array_2d_from_3d)




1D_to_2D:
[[0 1 2]
 [3 4 5]]

1D_to_3D:
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]

2D_to_1D:
[0 1 2 3 4 5]

2D_to_3D:
[[[0 1 2]
  [3 4 5]]]

3D_to_1D:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

3D_to_2D:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [9]:
# Q4_0111. 1차원 배열을 생성 후 2,3차원 배열로 변경하고 각 2,3차원 배열을 1,3차원 1,2차원 배열로 다시 변경해서 출력하세요.



import numpy as np

# 1차원 배열 생성
one_dimensional_array = np.arange(6)

# 1차원 배열을 2차원 배열로 변경
reshaped = one_dimensional_array.reshape(2, 3)
print("Reshaped Array:\n", reshaped)

# 배열 크기 조정 (Resize)
resized = np.resize(one_dimensional_array, (3, 2))
print("Resized Array:\n", resized)



Reshaped Array:
 [[0 1 2]
 [3 4 5]]
Resized Array:
 [[0 1]
 [2 3]
 [4 5]]


In [ ]:
# Q5_0111. 1차원 배열을 생성해서 2차원 배열로 변환한 후 다음 사항을 수행하세요

# 2차원 배열을 리스트로 타입 변경해보세요
# 리스트를 다시 배열로 변경하세요

import numpy as np

# 1차원 배열 생성
array_1d = np.arange(10)  # 예를 들어, 0부터 9까지의 숫자가 있는 배열

# 1차원 배열을 2차원 배열로 변환 (예: 5행 2열)
array_2d = array_1d.reshape(5, 2)

# 2차원 배열을 리스트로 변환
list_2d = array_2d.tolist()

# 리스트를 다시 배열로 변환
array_from_list = np.array(list_2d)

# 결과 출력
array_1d, array_2d, list_2d, array_from_list



In [10]:
# Q6_0111. 두 배열 [[1,2],[3,4]]와 [[5,6],[7,8]] 을 가로로 연결해보세요



import numpy as np

# 배열 생성
array1 = np.array([[1, 2], [3, 4]])

array2 = np.array([[5, 6], [7, 8]])

# 배열 가로로 연결
horizontal_concatenated = np.hstack((array1, array2))

# 결과 출력
print(horizontal_concatenated)


a = np.array([[1,2],[3,4]])
b = np.array( [[5,6],[7,8]])
c = np.concatenate((a,b), axis=1)
print(c)


[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [11]:
# Q7_0111. 두 배열 [[1,2,3]] 과 [[4,5,6]]을 세로로 연결해보세요

# 배열 생성
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4, 5, 6]])

# 배열을 세로로 연결
vertical_concatenated = np.vstack((array1, array2))

# 결과 출력
vertical_concatenated


array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# Q8_0111. 배열 [0,1,2,3,4,5,6,7,8]을 세 부분으로 나눠보세요 

# 배열 생성
array_to_split = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# 배열을 세 부분으로 나누기 위한 분할 지점 설정
split_indices = [3, 6]

# 배열 분할
split_arrays = np.split(array_to_split, split_indices)

# 분할된 배열 출력
print(split_arrays)


arr22 = np.array([0,1,2,3,4,5,6,7,8])

arr23, arr24, arr25 = np.split(arr22, 3)

print(arr23)
print(arr24)
print(arr25)


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[0 1 2]
[3 4 5]
[6 7 8]


In [ ]:
# Q9_0111. array2d에서 슬라이싱을 사용해서 아래와 같이 출력하는 코드를 만들어보세요

# 1.
# [[1 2]
# [4 5]]

# 2.
# (2가지 방법으로 뽑아보세요)
# [[4 5 6]
# [7 8 9]]

# 3.
# [[1 2 3]
# [4 5 6]
# [7 8 9]]

# 4.
# [[2 3]
# [5 6]]

# 5.
# [1 4]


# arr2d 배열 생성
array2d = np.arange(1, 10).reshape(3, 3)

# 각 요구사항에 맞는 슬라이싱
# 1. [[1 2] [4 5]]
slice1 = array2d[0:2, 0:2]

# 2. [[4 5 6] [7 8 9]] (두 가지 방법)
slice2a = array2d[1:3, :]      # 첫 번째 방법: 1~2행, 모든 열
slice2b = array2d[1:3, 0:3]    # 두 번째 방법: 1~2행, 0~2열

# 3. [[1 2 3] [4 5 6] [7 8 9]]
slice3 = array2d               # 전체 배열

# 4. [[2 3] [5 6]]
slice4 = array2d[0:2, 1:3]

# 5. [1 4]
slice5 = array2d[0:2, 0]       # 0~1행, 0열

slice1, slice2a, slice2b, slice3, slice4, slice5





In [13]:
# Q10_0111. 1~14 까지 ndarray를 만들어서 array_e로 저장하고 (array_e / 2) > 5 를 만족하는 값을 불린 인덱스로 출력하는 코드를 만드세요.

# 1부터 14까지의 ndarray 생성 및 array_e에 저장
array_e = np.arange(1, 15)

# (array_e / 2) > 5를 만족하는 값 불린 인덱스로 출력
result = array_e[(array_e / 2) > 5]
result




array([11, 12, 13, 14])

In [14]:
# Q11_0111. 1~100까지 정수에서 5의 배수이면서 2의 배수인 것만을 출력하는 코드를 만드세요 (for문과 배열 두가지 방식으로 만들어 보세요)

# for문을 사용하여 1부터 100까지 정수 중 5의 배수이면서 2의 배수인 것을 찾기
result_for = [num for num in range(1, 101) if num % 5 == 0 and num % 2 == 0]

# 넘파이 배열을 사용하여 같은 조건을 만족하는 값 찾기
array = np.arange(1, 101)
result_array = array[(array % 5 == 0) & (array % 2 == 0)]

result_for, result_array




([10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [15]:
# Q12_0111. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하는 코드 작성해주세요

# 표준정규분포로 구성된 5행 5열 다차원 배열 생성
array_normal = np.random.randn(5, 5)

# 평균과 표준편차 계산
mean = np.mean(array_normal)
std_dev = np.std(array_normal)

array_normal, mean, std_dev




(array([[ 0.75223977,  0.33787151,  2.35051848, -1.85747467,  1.30727047],
        [-1.43736932, -0.3336459 ,  0.11834658,  1.62012719,  0.00628932],
        [ 2.67349027,  1.19736683,  1.13693977,  1.08845889,  0.5194499 ],
        [ 0.08451416, -0.1200999 , -1.55845048,  0.27421911,  0.77831745],
        [ 0.56946711,  0.94754833,  0.20714433, -0.17021702, -0.14111333]]),
 0.4140483529650992,
 1.052009873689129)